### PR TITLE
added my name file

### PR DESCRIPTION
**Pull request by brittanyjoiner15**
added my name here! did i do this right?

### CODE REVIEW

**Comment by CristinaRuth** [comment]
@brittanyjoiner15 almost right! You're just missing the day of Oct in your folder structure 🙂

Try 2019/Oct 3/yourfile.md as the file/folder structure. Or Oct 4 if it applies to your part of the world 🙂

**Comment by brittanyjoiner15** [comment]
Okay i think i fixed that! Let me knwo if this worked... still new to this.

**Review by CristinaRuth — CHANGES_REQUESTED** [review]
@brittanyjoiner15  I'm seeing 3 files changed. We want to see 1 file :) 

Please delete the following files and you should be good!

* 2019/.DS_Store
* 2019/Oct/brittanyjoiner15.md

No worries about making mistakes. That's the goal here - to learn! You're doing great!

**Comment by brittanyjoiner15** [comment]
Done!! Thank you for your patience!

**Review by CristinaRuth — APPROVED** [review]
perfect!

**Comment by brittanyjoiner15** [comment]
thanks!! this is a great idea - super helpful. Appreciate you doing this!

**Comment by CristinaRuth** [comment]
You're welcome. Glad you found it helpful. 🙂

**Pull request merged**
